### ISSUE TITLE
NodeRunner isHeadless() check is inappropriate if using Tmux

### ISSUE THREAD

**Issue by george-hawkins** [corda/corda-gradle-plugins#18]
This issue follows on from #12 - the headless check that `NodeRunner` performs shouldn't be done if running under Tmux.

Currently the logic is to check if the environment is headless and only if it isn't does it then later (if the environment is Linux) check if it's running under Tmux (in which case it opens Tmux screens) or not (in which case it opens Xterms).

However if it's running under Tmux then it shouldn't care about whether the setup is headless (as Tmux doesn't depend on a graphical environment). To fix this find the following like in [`NodeRunner.kt`](https://github.com/corda/corda-gradle-plugins/blob/master/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt):

    val headless = GraphicsEnvironment.isHeadless() || args.contains(HEADLESS_FLAG)

And change it to:

    val headless = (GraphicsEnvironment.isHeadless() && !isTmux()) || args.contains(HEADLESS_FLAG)

As `isTmux()` is a simple environment variable check it'll work on Linux while not causing issues on non-Linux environments (where the `TMUX` environment variable is never set so the check will always return false).

**Comment by chrisr3** [comment]
This was fixed by Tushar Singh Bora on 20/07/2018.
