### ISSUE TITLE
Exclusions in jvmArgs are missing

### ISSUE THREAD

**Issue by Kokogino** [corda/corda-gradle-plugins#216]
The jvm arg of the quasar plugin is set via `jvmArgs "-javaagent:${project.configurations.quasar.singleFile}"` which results in `-javaagent:lib/quasar.jar`

An actual node has the jvm arg like:
```
-javaagent:lib/quasar.jar=x(antlr**;bftsmart**;co.paralleluniverse**;com.codahale**;com.esotericsoftware**;com.fasterxml**;com.google**;com.ibm**;com.intellij**;com.jcabi**;com.nhaarman**;com.opengamma**;com.typesafe**;com.zaxxer**;de.javakaffee**;groovy**;groovyjarjarantlr**;groovyjarjarasm**;io.atomix**;io.github**;io.netty**;jdk**;junit**;kotlin**;net.bytebuddy**;net.i2p**;org.apache**;org.assertj**;org.bouncycastle**;org.codehaus**;org.crsh**;org.dom4j**;org.fusesource**;org.h2**;org.hamcrest**;org.hibernate**;org.jboss**;org.jcp**;org.joda**;org.junit**;org.mockito**;org.objectweb**;org.objenesis**;org.slf4j**;org.w3c**;org.xml**;org.yaml**;reflectasm**;rx**;org.jolokia**)
```

All the exclusions in the quasar plugin are missing.
Visible on https://github.com/corda/corda/pull/4808/files

**Comment by chrisr3** [comment]
These exclusions on the Node look suspicious to me. Why would a Production Node need to exclude JUnit, Hamcrest and Mockito, for example? But adding the ability to exclude packages for Node Driver tests would definitely be a Good Thing.

**Comment by chrisr3** [comment]
Added to releases 4.0.45 and 5.0.1.
