### ISSUE TITLE
DockerForm expects docker-compose in build directory

### ISSUE THREAD

**Issue by sassit** [corda/corda-gradle-plugins#228]
I implemented a DockerForm gradle task, DockerForm expects a docker-compose.yml though in the build directory (I used a corda-starter-template project).

Looking at the DockerForm implementation I cannot find a way to override the location it is expecting a docker-compose file, it seems to be hardcoded to build/nodes. This directory is a build generated one obviously so I am not sure if this is a chicken or egg issue.

What is the proposed way to make use of the DockerForm, currently I manually copy an empty docker-compose file which can only mean that I don't understand the concept.

If anyone can give me a hint, would be great.

The error message on a clean(ed) build is:

19:36:09: Executing task 'deployNodes'...

> Task :contracts:compileKotlin UP-TO-DATE
> Task :contracts:compileJava NO-SOURCE
> Task :contracts:processResources NO-SOURCE
> Task :contracts:classes UP-TO-DATE
> Task :contracts:configureCordappFatJar
> Task :contracts:inspectClassesForKotlinIC UP-TO-DATE
> Task :contracts:jar UP-TO-DATE
> Task :workflows:compileKotlin UP-TO-DATE
> Task :workflows:compileJava NO-SOURCE
> Task :workflows:processResources UP-TO-DATE
> Task :workflows:classes UP-TO-DATE
> Task :workflows:configureCordappFatJar
> Task :workflows:inspectClassesForKotlinIC UP-TO-DATE
> Task :workflows:jar UP-TO-DATE
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :configureCordappFatJar
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :deployNodes FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':deployNodes'.
> File '/Users/sassit/Documents/Workspace/corda/cordapp-template/build/nodes/docker-compose.yml' specified for property 'dockerComposePath' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
14 actionable tasks: 4 executed, 10 up-to-date
File '/Users/sassit/Documents/Workspace/corda/cordapp-template/build/nodes/docker-compose.yml' specified for property 'dockerComposePath' does not exist.
19:36:10: Task execution finished 'deployNodes'.

**Comment by roastario** [comment]
this is addressed in: https://github.com/corda/corda-gradle-plugins/pull/234

**Comment by sassit** [comment]
Saw it, changed the semantics though, I worked around it and I was using a docker-compose to bootstrap other services too referencing the generated Dockerfiles. Will have to build a different approach. Thank you though.
