### ISSUE TITLE
Dockerfile breaks because of missing nss

### ISSUE THREAD

**Issue by sassit** [corda/corda-gradle-plugins#229]
I've hacked an issue that I raised to run DockerForm, I need to manually copy a docker-compose to the build nodes directory which I need to create before I can run deployNodes.

Once that is done the build runs through, I docker-compose up, the images are built and the startup of the container fails as there is a missing nss on the --nocache line of the Dockerfile in the plugins resources. 

I can get around it by manually adding the nss dependency. I found out that there is a known issue around it and the recommended approach is the one I mentioned.

Can this nss dependency be added/does it make sense to issue the pull request on it?

The error on startup is:

➜  nodes git:(release-V4) ✗ docker-compose up
Removing nodes_notary_1
Removing nodes_partyb_1
Recreating nodes_partya_1              ... done
Recreating b412436a4bb5_nodes_notary_1 ... done
Recreating a2ab1d363205_nodes_partyb_1 ... done
Attaching to nodes_partyb_1, nodes_notary_1, nodes_partya_1
notary_1  | Exception in thread "main" java.lang.ExceptionInInitializerError
notary_1  |     at net.corda.core.crypto.Crypto.<clinit>(Crypto.kt:78)
notary_1  |     at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:139)
notary_1  |     at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:108)
notary_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:184)
notary_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:152)
notary_1  |     at picocli.CommandLine.execute(CommandLine.java:1056)
notary_1  |     at picocli.CommandLine.access$900(CommandLine.java:142)
notary_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
notary_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
notary_1  |     at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
notary_1  |     at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
notary_1  |     at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:72)
notary_1  |     at net.corda.node.Corda.main(Corda.kt:13)
notary_1  | Caused by: java.security.ProviderException: Could not initialize NSS
notary_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:223)
notary_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
notary_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
notary_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
notary_1  |     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
notary_1  |     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
notary_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
notary_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
notary_1  |     at java.security.AccessController.doPrivileged(Native Method)
notary_1  |     at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
notary_1  |     at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
notary_1  |     at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
notary_1  |     at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
notary_1  |     at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
notary_1  |     at java.security.Security.insertProviderAt(Security.java:395)
notary_1  |     at net.corda.core.crypto.internal.ProviderMapKt.<clinit>(ProviderMap.kt:28)
notary_1  |     ... 13 more
notary_1  | Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
notary_1  |     at sun.security.pkcs11.Secmod.initialize(Secmod.java:193)
notary_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218)
notary_1  |     ... 28 more
partyb_1  | Exception in thread "main" java.lang.ExceptionInInitializerError
partyb_1  |     at net.corda.core.crypto.Crypto.<clinit>(Crypto.kt:78)
partyb_1  |     at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:139)
partyb_1  |     at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:108)
partyb_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:184)
partyb_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:152)
partyb_1  |     at picocli.CommandLine.execute(CommandLine.java:1056)
partyb_1  |     at picocli.CommandLine.access$900(CommandLine.java:142)
partyb_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
partyb_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
partyb_1  |     at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
partyb_1  |     at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
partyb_1  |     at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:72)
partyb_1  |     at net.corda.node.Corda.main(Corda.kt:13)
partyb_1  | Caused by: java.security.ProviderException: Could not initialize NSS
partyb_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:223)
partyb_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
partyb_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
partyb_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
partyb_1  |     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
partyb_1  |     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
partyb_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
partyb_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
partyb_1  |     at java.security.AccessController.doPrivileged(Native Method)
partyb_1  |     at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
partyb_1  |     at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
partyb_1  |     at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
partyb_1  |     at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
partyb_1  |     at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
partyb_1  |     at java.security.Security.insertProviderAt(Security.java:395)
partyb_1  |     at net.corda.core.crypto.internal.ProviderMapKt.<clinit>(ProviderMap.kt:28)
partyb_1  |     ... 13 more
partyb_1  | Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
partyb_1  |     at sun.security.pkcs11.Secmod.initialize(Secmod.java:193)
partyb_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218)
partyb_1  |     ... 28 more
partya_1  | Exception in thread "main" java.lang.ExceptionInInitializerError
partya_1  |     at net.corda.core.crypto.Crypto.<clinit>(Crypto.kt:78)
partya_1  |     at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:139)
partya_1  |     at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:108)
partya_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:184)
partya_1  |     at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:152)
partya_1  |     at picocli.CommandLine.execute(CommandLine.java:1056)
partya_1  |     at picocli.CommandLine.access$900(CommandLine.java:142)
partya_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
partya_1  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
partya_1  |     at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
partya_1  |     at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
partya_1  |     at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:72)
partya_1  |     at net.corda.node.Corda.main(Corda.kt:13)
partya_1  | Caused by: java.security.ProviderException: Could not initialize NSS
partya_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:223)
partya_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
partya_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
partya_1  |     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
partya_1  |     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
partya_1  |     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
partya_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
partya_1  |     at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
partya_1  |     at java.security.AccessController.doPrivileged(Native Method)
partya_1  |     at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
partya_1  |     at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
partya_1  |     at sun.security.jca.ProviderList.loadAll(ProviderList.java:282)
partya_1  |     at sun.security.jca.ProviderList.removeInvalid(ProviderList.java:299)
partya_1  |     at sun.security.jca.Providers.getFullProviderList(Providers.java:173)
partya_1  |     at java.security.Security.insertProviderAt(Security.java:395)
partya_1  |     at net.corda.core.crypto.internal.ProviderMapKt.<clinit>(ProviderMap.kt:28)
partya_1  |     ... 13 more
partya_1  | Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
partya_1  |     at sun.security.pkcs11.Secmod.initialize(Secmod.java:193)
partya_1  |     at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218)
partya_1  |     ... 28 more
nodes_notary_1 exited with code 1
nodes_partyb_1 exited with code 1
nodes_partya_1 exited with code 1

**Comment by bertschneider** [comment]
As far as I understand it the bug in Alpine Linux is already fixed and a new base docker image should be available.

https://bugs.alpinelinux.org/issues/10126

**Comment by bertschneider** [comment]
The current OpenJDK base image `openjdk:8u212-jre-alpine` seems to work fine. Sadly I can not fine the base image definition in the code to create a pull request.

**Comment by sassit** [comment]
Thank you Bert, latest version is using the official corda docker image, Dockerfile became obsolete therefore. Will close it.

**Comment by bertschneider** [comment]
But I could not find version 5.0.2 at Maven Central or any other repository. Isn't it available yet or did I just miss it?
