### ISSUE TITLE
deployNodes creates only one party folder if the nodes have the same Organization

### ISSUE THREAD

**Issue by cxyzhang0** [corda/corda-gradle-plugins#243]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

* A clear description of the issue
* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)
* Steps to reproduce the issue
* The version/tag/release or commit hash it occured on

**Comment by cxyzhang0** [comment]
Currently, in the gradle task deployNodes, if two or more nodes' names have the same O, then only one party folder is created.
It would be nice to be able to use CN, OU and O to determine the folder name. So CN ?: OU ?: O.
Let me know if a PR is needed.
Thanks.

\Sean

**Comment by cxyzhang0** [comment]
Will this work?
In rootDir function in Node.kt, define dirName as follows:
        val commonName = name!!.trim().split(",").firstOrNull { it.startsWith("CN=") }?.substringAfter("=")
        val organizationUnitName = name!!.trim().split(",").firstOrNull { it.startsWith("OU=") }?.substringAfter("=")
        val organizationName = name!!.trim().split(",").firstOrNull { it.startsWith("O=") }?.substringAfter("=")
        val dirName = commonName ?: organizationUnitName ?: organizationName ?: name

**Comment by cxyzhang0** [comment]
A little refactoring -
        val nameParts = name!!.trim().split(",")
        val commonName = nameParts.firstOrNull { it.startsWith("CN=") }?.substringAfter("=")
        val organizationUnitName = nameParts.firstOrNull { it.startsWith("OU=") }?.substringAfter("=")
        val organizationName = nameParts.firstOrNull { it.startsWith("O=") }?.substringAfter("=")
        val dirName = commonName ?: organizationUnitName ?: organizationName ?: name

**Comment by hbish** [comment]
I have ran into the same issue I have raised a PR #252

**Comment by chrisr3** [comment]
Fixed in Plugins 4.0.46.
