### ISSUE TITLE
Option to turn off plain text passwords in stdout during signing

### ISSUE THREAD

**Issue by dazraf** [corda/corda-gradle-plugins#303]
It appears that the current release outputs the signing `storepass` and `keypass` passwords as plain text to files. This is a problem for open source cordapps that expose the build output to contributors. Can we please have an option to not print out passwords? Ideally this should be environment driven so that it cannot be turned off by contributors. 

Thanks.

**Comment by mnesbit** [comment]
Can you attach a log please

**Comment by dazraf** [comment]
Thanks @mnesbit. Sample log with password masked manually:

```
if you need the logs to attach :
Task ':cordite-cordapp:jar' is not up-to-date because:
   No history is available.
 Jar signing with following options: {alias=cordite, storepass=****, keystore=/tmp/keystore.jks, storetype=JKS, keypass=****, jar=/builds/cordite/cordite/cordapps/cordite-cordapp/build/libs/cordite-cordapp-0.4.9-SNAPSHOT.jar}
```

**Comment by dazraf** [comment]
Thanks @mnesbit 
Here's the log output, passwords manually masked by us:

```
Task ':cordite-cordapp:jar' is not up-to-date because:
   No history is available.
 Jar signing with following options: {alias=cordite, storepass=****, keystore=/tmp/keystore.jks, storetype=JKS, keypass=****, jar=/builds/cordite/cordite/cordapps/cordite-cordapp/build/libs/cordite-cordapp-0.4.9-SNAPSHOT.jar}
```
