### ISSUE TITLE
Cordaformation plugin does not copy CorDapps to fully-qualified JAR filenames

### ISSUE THREAD

**Issue by nsmith00** [corda/corda-gradle-plugins#360]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

* A clear description of the issue
* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)
* Steps to reproduce the issue
* The version/tag/release or commit hash it occured on

**Comment by nsmith00** [comment]
The `deployNodes` task saves the dependent CorDapps copied from the source repository to the node `cordapps` directories using only the artifact name and version (as is stored in the repository). This causes the plugin to overwrite CorDapps which have the same artifact name.

This issue occurs with corda-gradle-plugins version 5.0.13

**Comment by chrisr3** [comment]
> The `deployNodes` task saves the dependent non-project CorDapps copied from the source repository to the node `cordapps` directories using only the artifact name and version (as is stored in the repository). This causes the plugin to overwrite CorDapps which have the same artifact name.

Hi, thanks for your report. However, I don't think I understand the issue. The `cordformation` plugin is installing the CorDapp with the precise file name that it has in the remote repository - which includes both its artifact name and version. Are you trying also to install a _different_ CorDapp which nonetheless has the exact same file name (including its artifact name and version number) as the remote CorDapp? In which case, it would seem that we _could_ modify `cordformation`, but this wouldn't change the fundamental problem which is that you would still have two different CorDapps with the same file name.

> This issue occurs with corda-gradle-plugins version 5.0.13

FYI the latest release version is still 5.0.12.

**Comment by nsmith00** [comment]
Hi,
I probably didn’t specify the issue too well, The problem occurs when installing multiple cordapps that have the same artifact name and version but different group names onto a node. As the plugin uses only the artifact name and version to create the name of the destination JAR, cordapps can be overwitten by other cordapps It can be argued that the plugin is using the precise artifact name of the file in the repository, but for us it is ignoring the qualifying group name (which in a maven repository is the name of the grandparent directory of the artifact).

Kind regards,

Nick

**Comment by chrisr3** [comment]
> The problem occurs when installing multiple cordapps that have the same artifact name and version but different group names onto a node.

Yes, but in that case you have _still_ created multiple different CorDapps with the exact same file names. The `cordformation` plugin is simply using the file names as they exist in the remote repositories, as they are understood by both Maven and Gradle.

Instead of asking all `cordformation` users to start downloading and installing CorDapps with file names that they do not expect, have you considered giving your own CorDapps unique artifact names in the first place?

**Comment by nsmith00** [comment]
Hi Chris,

In maven terminology the cordformation plugin is ‘flattening’ the repo when copying the JAR files and in such cases the plugins always prepends the group name to avoid naming collisions, We have naturally discussed having unique artifact names for our cord apps but decided to raise this issue as we have unique group names which otherwise would be wasted,

Kind regards,

Nick

**Comment by nsmith00** [comment]
I would additionally say that I would absolutely agree that prepending the gradle/maven group name to the destination would be optional (and by default disabled) as users obviously we are the first to raise this issue. For your information, it is intended that we install cordapps from several vendors on the same node which could potentially have the same artifact name.

Kind regards,

Nick

**Comment by chrisr3** [comment]
> I would additionally say that I would absolutely agree that prepending the gradle/maven group name to the destination would be optional (and by default disabled) as users obviously we are the first to raise this issue. For your information, it is intended that we install cordapps from several vendors on the same node which could potentially have the same artifact name. Kind regards, Nick
