### ISSUE TITLE
Can't Set emailAddress in Cordform Node

### ISSUE THREAD

**Issue by opticyclic** [corda/corda-gradle-plugins#384]
If you don't set a value the node.conf, `emailAddress` defaults to `"you@example.com"`
https://github.com/corda/corda/blob/release/os/4.8/node/src/main/resources/corda-reference.conf#L12

I'd like to be able to set this in the Cordform node definition.

**Comment by chrisr3** [comment]
> I'd like to be able to set this in the Cordform node definition.

Thanks for the report. Have you tried adding the new email address in the `extraConfig` block?
```groovy
node {
    ...
    extraConfig = [
        'emailAddress': 'evil@bunny.com'
    ]
    ...
}
```

**Comment by chrisr3** [comment]
I am assuming that the `extraConfig` block has been enough here.
