### ISSUE TITLE
runMigrationScripts=true does not create app-schemas

### ISSUE THREAD

**Issue by amolpednekar** [corda/corda-gradle-plugins#390]
Corda version: Corda OS 4.7

In my CorDapp, I have defined some custom schemas by implementing queryable state. I have not defined any liquibase migration scripts.

My deploy node task looks like this

```
task deployNodes(type: net.corda.plugins.Cordform, dependsOn: ['jar']) {
    ......
    node {
        name "O=PartyA,L=London,C=GB"
        .......
        runSchemaMigration = true
    }
}
```

As per this article - https://www.corda.net/blog/continuing-database-harmonization-between-corda-and-corda-enterprise/ 
Using "runMigrationScripts _"will by default run both core and app schemas and node will be ready to run."_

I had that in my deployNodes task -> and executed runNodes - It showed exceptions saying there are missing tables [app-tables]

```
Incompatible schema change detected. Please run schema migration scripts (node with sub-command run-migration-scripts)
4:45
.../
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [xyz]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121) ~[h
```

But when I used `runnodes --allow-hibernate-to-manage-app-schema`; It worked; pointing to the fact that the app-schemas werent created, only core-schemas were. 

Which is not expected based on the comment in the article. Can you confirm?

**Comment by blsemo** [comment]
Hi,

`runSchemaMigration = true` only runs liquibase scripts - it assumes that app developers provide a liquibase migration script for their custom schema. If you did not define liquibase scripts for your app schema, it will not be able to pick them up. You need to provide liquibase schemas anyway for any CorDapp you want to run in a production environment.
While you are developing/testing, you can get away without liquibase scripts by providing the `--allow-hibernate-to-manage-app-schema` flag at runtime - this is a convenience shortcut so you can experiment with schemas/apps without having to edit liquibase scripts all the time, but does not replace having to formalise the schema in a script eventually.

**Comment by amolpednekar** [comment]
@blsemo Understood. Since `deployNodes` task is generally meant for deployment only, having "--allow-hibernate-to-manage-app-schema" type behaviour in cordform plugin would be really useful, so I guess that's a feature request.

Or, is there a Corda tool that allows generation of liquibase scripts? Because writing them by hand when there are many entities and data models are changing (during rapid development phases) is quite tedious.

**Comment by opticyclic** [comment]
https://github.com/corda/corda/issues/6813 is the issue for Corda to generate the liquibase scripts automatically.
