### ISSUE TITLE
./gradlew deployNodes: java.lang.StackOverflowError (no error message)

### ISSUE THREAD

**Issue by dkelly103** [corda/corda-gradle-plugins#495]
## Expected Behavior

- The `deployNodes` task runs successfully.

## Actual Behavior

- The task fails with the following output:

                        ./gradlew clean deployNodes --no-daemon --warning-mode=all
                        
                        > Task :app:workflows:compileJava
                        Note: Some input files use unchecked or unsafe operations.
                        Note: Recompile with -Xlint:unchecked for details.
                        
                        > Task :jar
                        Cordapp metadata not defined for this gradle build file. See https://docs.corda.net/head/cordapp-build-systems.html#separation-of-cordapp-contracts-flows-and-services
                        
                        > Task :deployNodes FAILED
                        Running Cordform task
                        Deleting /home/user/cordapps/build/nodes
                        Bootstrapping local test network in /home/user/cordapps/build/nodes
                        Generating node directory for Notary
                        Generating node directory for PartyA
                        Generating node directory for PartyB
                        
                        FAILURE: Build failed with an exception.
                        
                        * What went wrong:
                        Execution failed for task ':deployNodes'.
                        > org.gradle.api.InvalidUserCodeException (no error message)
                           > java.lang.StackOverflowError (no error message)
                        
                        * Try:
                        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                        
                        * Get more help at https://help.gradle.org
                        
                        BUILD FAILED in 26s
                        49 actionable tasks: 39 executed, 10 up-to-date
                        Exception in thread "Thread-46" java.lang.NoClassDefFoundError: kotlin/Unit
                                at net.corda.node.utilities.logging.AsyncLoggerContextSelectorNoThreadLocal$1.invoke(AsyncLoggerContextSelectorNoThreadLocal.kt:12)
                                at net.corda.nodeapi.internal.ShutdownHookKt$addShutdownHook$hook$1.run(ShutdownHook.kt:15)
                                at java.lang.Thread.run(Thread.java:748)
                        Caused by: java.lang.ClassNotFoundException: kotlin.Unit
                                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
                                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                                ... 3 more

## Specifications

  - Version:
     - gradle: 5.6.4
     - gradle dependencies copied grom latest java cordapp examples: 

                            cordaReleaseGroup=net.corda
                            cordaCoreReleaseGroup=net.corda
                            cordaVersion=4.8.5
                            cordaCoreVersion=4.8.5
                            gradlePluginsVersion=5.0.12
                            kotlinVersion=1.2.71
                            junitVersion=4.12
                            quasarVersion=0.7.10
                            log4jVersion =2.17.1
                            platformVersion=10
                            slf4jVersion=1.7.25
                            nettyVersion=4.1.22.Final

## Context

My task was originally working fine, but then I started to see the above error when I added a new dependency (no code changes). The dependency was a custom library for producing Red Hat AMQ messages and has the following child dependencies:

          org.springframework.boot:spring-boot-starter-web:2.2.0.RELEASE
          org.apache.activemq:artemis-jms-client:2.10.1 (*)
          org.springframework:spring-jms:2.5
          javax.json:javax.json-api:1.0

Any idea whats going on here?

Update 1: The cordapp jar builds fine. It's only the deployNodes task that fails.

**Comment by chrisr3** [comment]
The last time I saw errors like that it was because Gradle was using an incompatible version of the JVM. What version of the JVM are you running Corda on? The Quasar Java agent used by Corda is sensitive to this:
- Quasar 0.7.x requires Java 8
- Quasar 0.8.x requires Java 11+

**Comment by dkelly103** [comment]
I’ve tried with both 8 and 11. Both are failing with the same error 



gradlew.bat --version

 

------------------------------------------------------------

Gradle 5.6.4

------------------------------------------------------------

 

Build time:   2019-11-01 20:42:00 UTC

Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

 

Kotlin:       1.3.41

Groovy:       2.5.4

Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019

JVM:          11.0.11 (Oracle Corporation 11.0.11+9-LTS-194)

OS:           Windows 10 10.0 amd64

 

 

 

 

 

 

./gradlew --version

 

------------------------------------------------------------

Gradle 5.6.4

------------------------------------------------------------

 

Build time:   2019-11-01 20:42:00 UTC

Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

 

Kotlin:       1.3.41

Groovy:       2.5.4

Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019

JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)

OS:           Linux 3.10.0-1160.53.1.el7.x86_64 amd64

**Comment by chrisr3** [comment]
```
gradlePluginsVersion=5.0.12
quasarVersion=0.7.10
```
Are you _really_ using Quasar 0.7.10? You _should_ be using 0.7.13_r3 with Corda 4.8.5. The latest Corda Gradle plugins version is 5.0.15 as well.

**Comment by dkelly103** [comment]
I debugged the task in IntelliJ and found that the following if statement evaluated to true.

 

                private LoggerContext validateContext(final LoggerContext context) {

                        if (TO_SLF4J_CONTEXT.equals(context.getClass().getName())) {

                                throw new LoggingException("log4j-slf4j-impl cannot be present with log4j-to-slf4j");

                        }

                        return context;

                }

 

The solution was to add this exclusion in the build.gradle

 

                configurations {

                        all {

                                exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'

                        }

                }

 

The deployNodes task runs okay now. I think we can close this issue. Thanks for the help!

**Comment by chrisr3** [comment]
I'm glad you've resolved this, but you also _really_ need to upgrade `quasarVersion` from 0.7.10 to 0.7.13_r3 because otherwise you've missing some important changes.

**Comment by dkelly103** [comment]
Yes, I didn’t update all the dependencies to the latest. Issue was still there and then I found this.
